# Generated by Django 3.2.12 on 2022-05-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('original_title', models.TextField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('release_date', models.TextField()),
                ('runtime', models.IntegerField()),
                ('popularity', models.FloatField()),
                ('adult', models.BooleanField()),
                ('like_users', models.IntegerField()),
                ('genre', models.IntegerField()),
            ],
        ),
    ]
